### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [bougenville/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by bougenville** [comment]
Hi Joe, thanks for the comment. As I mentioned in README file, I got this theme from my mentor a few years ago, but I believe it belongs to someone else. So I did some research and found that this theme is based on [dallas.zsh-theme](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/dallas.zsh-theme) with only some fonts color tweaked. The screenshot is as the following:

<img width="542" alt="my zsh-theme" src="https://user-images.githubusercontent.com/57277705/68086294-4435e900-fe85-11e9-9d43-bbb76aaa8a19.png">


As to the license, do I against the law if I make this repo open without providing a license file? Or should I follow the [oh-my-zsh project](https://github.com/robbyrussell/oh-my-zsh) by using MIT license?

Thanks!

**Comment by unixorn** [comment]
Since it's a variant of [dallas](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/dallas.zsh-theme), which is MIT licensed, you should document that in the readme and add an MIT License file.

Then all you'll need to do is add a screen shot and it'll be ok to add.

thanks!

**Comment by bougenville** [comment]
Hi Joe, I rewrite the README file, and the screen shot and an MIT License file are added as well.

Thanks for your help again.

**Comment by unixorn** [comment]
Thanks, adding in https://github.com/unixorn/awesome-zsh-plugins/pull/817
